# Generated by Django 3.2.4 on 2021-06-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(max_length=7)),
                ('nationality', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('pin_code', models.IntegerField()),
                ('qualification', models.CharField(max_length=15)),
                ('salary', models.CharField(max_length=10)),
                ('PAN', models.IntegerField()),
            ],
        ),
    ]
